CREATE TABLE user(
		id INT NOT NULL AUTO_INCREMENT,
		email VARCHAR(255) NOT NULL,
		created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  		updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		PRIMARY KEY (id),
		INDEX(email)
);
	
CREATE TABLE profile(
		id INT NOT NULL AUTO_INCREMENT,
		user_id INT NOT NULL,
		name TEXT,
		role VARCHAR(12) DEFAULT 'USER',
		created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  		updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		PRIMARY KEY (id),
		FOREIGN KEY (user_id) REFERENCES user(id)
);


CREATE TABLE post(
		id INT NOT NULL AUTO_INCREMENT,
		user_id INT NOT NULL,
		title TEXT,
  		updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		PRIMARY KEY (id),
		FOREIGN KEY (user_id) REFERENCES user(id)
);


INSERT INTO user (email) VALUES ('default_email@domain.com');
INSERT INTO profile (user_id,name,role) VALUES (1,'admin','ADMIN');
INSERT INTO post (user_id,title) VALUES (1,'this is a title');